import { db, booksTable } from "@workspace/db";
import { logger } from "./lib/logger";

const SEED_BOOKS = [
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    authorBio: "Matt Haig is a British author known for thoughtful, philosophical fiction that explores meaning and mental health.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0525559477-L.jpg",
    genre: "Fiction",
    tags: ["philosophical", "uplifting", "contemporary"],
    rating: 4.4,
    ratingsCount: 1820000,
    pages: 304,
    year: 2020,
    shortDescription: "Between life and death is a library where every book is a different version of your life.",
    description: "Nora Seed finds herself in a strange library between life and death, where each book lets her sample a different life she could have led. A meditation on regret, possibility, and the quiet beauty of an ordinary day.",
    trendingScore: 95,
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    authorBio: "Andy Weir is the bestselling author of The Martian. He writes meticulously researched, optimistic science fiction.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0593135202-L.jpg",
    genre: "Science Fiction",
    tags: ["space", "first-contact", "fast-paced"],
    rating: 4.6,
    ratingsCount: 940000,
    pages: 496,
    year: 2021,
    shortDescription: "A lone astronaut must save humanity — and figures out he's not alone after all.",
    description: "Ryland Grace wakes up on a spaceship with no memory of how he got there. Slowly he realizes he is humanity's last hope, and the bonds he forms in deep space become the heart of an extraordinary survival story.",
    trendingScore: 92,
  },
  {
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    authorBio: "Kazuo Ishiguro is a Nobel laureate known for restrained, emotionally devastating novels about memory and identity.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/059331817X-L.jpg",
    genre: "Science Fiction",
    tags: ["literary", "ai", "tender"],
    rating: 4.0,
    ratingsCount: 320000,
    pages: 320,
    year: 2021,
    shortDescription: "An artificial friend observes the world from a shop window, hoping to be chosen.",
    description: "Klara is an Artificial Friend with extraordinary observational qualities. From her place in the store, she watches the behavior of those who come in to browse, and of those who pass on the street outside. A luminous look at love, loneliness, and what makes us human.",
    trendingScore: 78,
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    authorBio: "Taylor Jenkins Reid writes glamorous, character-driven fiction about ambition, love, and the cost of fame.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/1501161938-L.jpg",
    genre: "Romance",
    tags: ["historical", "old-hollywood", "lgbtq"],
    rating: 4.5,
    ratingsCount: 2100000,
    pages: 400,
    year: 2017,
    shortDescription: "A reclusive Hollywood icon finally tells the story of her seven marriages.",
    description: "Aging Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself.",
    trendingScore: 96,
  },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    authorBio: "Delia Owens is a wildlife scientist whose debut novel became an international phenomenon.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0735219109-L.jpg",
    genre: "Mystery",
    tags: ["atmospheric", "coming-of-age", "nature"],
    rating: 4.4,
    ratingsCount: 2800000,
    pages: 384,
    year: 2018,
    shortDescription: "A girl raised alone in the marshes is accused of a small town's biggest crime.",
    description: "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet fishing village. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark.",
    trendingScore: 88,
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    authorBio: "Alex Michaelides is a screenwriter and novelist whose psychological thrillers have sold millions worldwide.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/1250301696-L.jpg",
    genre: "Mystery",
    tags: ["psychological", "twisty", "fast-paced"],
    rating: 4.2,
    ratingsCount: 1500000,
    pages: 336,
    year: 2019,
    shortDescription: "A woman shoots her husband five times — and never speaks another word.",
    description: "Alicia Berenson's life is seemingly perfect until she shoots her husband in the head five times and then never speaks another word. A criminal psychotherapist becomes obsessed with uncovering her motive.",
    trendingScore: 85,
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    authorBio: "James Clear is a writer and speaker focused on habits, decision-making, and continuous improvement.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0735211299-L.jpg",
    genre: "Self-Help",
    tags: ["productivity", "habits", "practical"],
    rating: 4.7,
    ratingsCount: 950000,
    pages: 320,
    year: 2018,
    shortDescription: "Tiny changes, remarkable results — a proven framework for improving every day.",
    description: "An easy and proven way to build good habits and break bad ones. Clear distills the most influential ideas in behavioral science and tells inspiring stories of how the principles work in practice.",
    trendingScore: 94,
  },
  {
    title: "Educated",
    author: "Tara Westover",
    authorBio: "Tara Westover earned her PhD from Cambridge after growing up in a survivalist family in rural Idaho.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0399590501-L.jpg",
    genre: "Memoir",
    tags: ["family", "education", "resilience"],
    rating: 4.5,
    ratingsCount: 980000,
    pages: 352,
    year: 2018,
    shortDescription: "A young woman raised off-grid in the mountains finds her way to Cambridge.",
    description: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her quest for knowledge transformed her — taking her over oceans and across continents.",
    trendingScore: 80,
  },
  {
    title: "Circe",
    author: "Madeline Miller",
    authorBio: "Madeline Miller is a classicist whose lyrical reimaginings of Greek myth have become modern classics.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0316556343-L.jpg",
    genre: "Fantasy",
    tags: ["mythology", "lyrical", "feminist"],
    rating: 4.3,
    ratingsCount: 700000,
    pages: 400,
    year: 2018,
    shortDescription: "The witch goddess Circe finds her power on a lonely island in the sea.",
    description: "In the house of Helios, god of the sun, a daughter is born. But Circe has neither the look of her father nor the voice of her mother. Turning to the world of mortals, she discovers her power: witchcraft.",
    trendingScore: 82,
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    authorBio: "Yuval Noah Harari is a historian and philosopher whose sweeping books reframe how we see the human story.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0062316095-L.jpg",
    genre: "History",
    tags: ["big-ideas", "anthropology", "deep"],
    rating: 4.5,
    ratingsCount: 1100000,
    pages: 464,
    year: 2015,
    shortDescription: "A sweeping account of the rise of Homo sapiens from foragers to gods.",
    description: "From a tiny species of insignificant apes living in the corner of Africa, Homo sapiens has come to dominate the planet. Harari traces 70,000 years of cognitive, agricultural, and scientific revolutions.",
    trendingScore: 76,
  },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    authorBio: "Madeline Miller is a classicist whose lyrical reimaginings of Greek myth have become modern classics.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0062060627-L.jpg",
    genre: "Fantasy",
    tags: ["mythology", "tragic-romance", "lyrical"],
    rating: 4.4,
    ratingsCount: 850000,
    pages: 416,
    year: 2012,
    shortDescription: "The story of Achilles and Patroclus — a love that shapes a war and a legend.",
    description: "Greece in the age of heroes. Patroclus, an awkward young prince, is exiled to the kingdom of Phthia. Here he is nobody, just another unwanted boy living in the shadow of King Peleus and his golden son, Achilles.",
    trendingScore: 90,
  },
  {
    title: "Pachinko",
    author: "Min Jin Lee",
    authorBio: "Min Jin Lee writes sweeping historical fiction about Korean diaspora, identity, and family.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/1455563935-L.jpg",
    genre: "Fiction",
    tags: ["historical", "family-saga", "literary"],
    rating: 4.3,
    ratingsCount: 380000,
    pages: 496,
    year: 2017,
    shortDescription: "Four generations of a Korean family chase belonging in 20th century Japan.",
    description: "In the early 1900s, teenaged Sunja, the adored daughter of a crippled fisherman, falls for a wealthy stranger. So begins a sweeping saga of an exceptional family in exile from its homeland.",
    trendingScore: 70,
  },
  {
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    authorBio: "Gabrielle Zevin is the bestselling author of literary novels that take pop culture seriously.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0593321200-L.jpg",
    genre: "Fiction",
    tags: ["friendship", "creativity", "video-games"],
    rating: 4.2,
    ratingsCount: 620000,
    pages: 416,
    year: 2022,
    shortDescription: "Two childhood friends become rival, partner, and the great love of each other's life — through games.",
    description: "Two friends — often in love, but never lovers — come together as creative partners in the world of video game design, where success brings them fame, joy, tragedy, duplicity, and ultimately a kind of immortality.",
    trendingScore: 91,
  },
  {
    title: "A Gentleman in Moscow",
    author: "Amor Towles",
    authorBio: "Amor Towles writes elegant, witty fiction about manners, time, and the persistence of grace.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0670026190-L.jpg",
    genre: "Fiction",
    tags: ["historical", "elegant", "slow-burn"],
    rating: 4.5,
    ratingsCount: 540000,
    pages: 480,
    year: 2016,
    shortDescription: "A Russian count is sentenced to spend his life inside a grand Moscow hotel.",
    description: "In 1922, Count Alexander Rostov is deemed an unrepentant aristocrat by a Bolshevik tribunal and sentenced to house arrest in the Metropol, a grand hotel across the street from the Kremlin.",
    trendingScore: 73,
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    authorBio: "Frank Herbert was an American science fiction writer whose epic Dune series redefined the genre.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0441172717-L.jpg",
    genre: "Science Fiction",
    tags: ["epic", "world-building", "political"],
    rating: 4.6,
    ratingsCount: 1300000,
    pages: 688,
    year: 1965,
    shortDescription: "On the desert planet Arrakis, control of a single resource will reshape the universe.",
    description: "Set on the desert planet Arrakis, Dune is the story of Paul Atreides, whose family accepts stewardship of the planet — and is drawn into a betrayal that will alter the course of the universe.",
    trendingScore: 86,
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    authorBio: "Patrick Rothfuss is a fantasy author known for lyrical prose and meticulously crafted worlds.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0756404746-L.jpg",
    genre: "Fantasy",
    tags: ["epic", "magic", "music"],
    rating: 4.5,
    ratingsCount: 920000,
    pages: 662,
    year: 2007,
    shortDescription: "A legendary wizard, hidden as an innkeeper, finally tells the story of his life.",
    description: "Told in Kvothe's own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen — a story of love, magic, and music.",
    trendingScore: 84,
  },
  {
    title: "Born a Crime",
    author: "Trevor Noah",
    authorBio: "Trevor Noah is a comedian and former host of The Daily Show. He grew up in apartheid-era South Africa.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0399588175-L.jpg",
    genre: "Memoir",
    tags: ["humor", "south-africa", "family"],
    rating: 4.7,
    ratingsCount: 770000,
    pages: 304,
    year: 2016,
    shortDescription: "A boy whose very existence was a crime tells the story of growing up in apartheid.",
    description: "Trevor Noah's unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Born to a white Swiss father and a black Xhosa mother, Trevor was born a crime.",
    trendingScore: 81,
  },
  {
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    authorBio: "Bonnie Garmus is a copywriter turned debut novelist whose first book became an international bestseller.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/038554734X-L.jpg",
    genre: "Fiction",
    tags: ["1960s", "feminist", "warm"],
    rating: 4.5,
    ratingsCount: 880000,
    pages: 400,
    year: 2022,
    shortDescription: "A 1960s chemist becomes a reluctant cooking-show host — and a quiet revolutionary.",
    description: "Chemist Elizabeth Zott is not your average woman. In 1961, when her all-male team at Hastings Research Institute fails to take her work seriously, she's forced to reinvent her life — first as a single mother, then as the star of a cooking show.",
    trendingScore: 89,
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    authorBio: "Daniel Kahneman was a Nobel-prize winning psychologist who pioneered behavioral economics.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/0374533555-L.jpg",
    genre: "Self-Help",
    tags: ["psychology", "decision-making", "academic"],
    rating: 4.4,
    ratingsCount: 480000,
    pages: 499,
    year: 2011,
    shortDescription: "Two systems of thought drive every decision you make — and one of them is wrong a lot.",
    description: "In the international bestseller, Daniel Kahneman explains the two systems that drive the way we think — System 1 is fast and intuitive; System 2 is slower and more deliberative. He exposes the faults of each.",
    trendingScore: 65,
  },
  {
    title: "Normal People",
    author: "Sally Rooney",
    authorBio: "Sally Rooney is an Irish novelist whose precise, intimate fiction has defined a literary generation.",
    coverUrl: "https://covers.openlibrary.org/b/isbn/1984822178-L.jpg",
    genre: "Romance",
    tags: ["literary", "intimate", "ireland"],
    rating: 4.0,
    ratingsCount: 690000,
    pages: 273,
    year: 2018,
    shortDescription: "Two Irish students orbit each other from secondary school to university and beyond.",
    description: "At school, Connell and Marianne pretend not to know each other. He's popular and well-adjusted, she's lonely and proud. But when they both leave their hometown for university, a strange and indelible connection grows between them.",
    trendingScore: 74,
  },
];

async function seed() {
  const existing = await db.select().from(booksTable);
  if (existing.length > 0) {
    logger.info({ count: existing.length }, "Books already seeded");
    return;
  }
  await db.insert(booksTable).values(SEED_BOOKS);
  logger.info({ count: SEED_BOOKS.length }, "Seeded books");
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    logger.error({ err }, "Seed failed");
    process.exit(1);
  });
